IMAGES_FOLDER_NAME = 'images'
FONTS_FOLDER_NAME = 'fonts'
REPORTS_FOLDER_NAME = 'reports'
RESOURCES_FOLDER_NAME = 'resources'

RESOURCES_FOLDER_PATH = f'./{RESOURCES_FOLDER_NAME}'
IMAGES_FOLDER_PATH = f'{RESOURCES_FOLDER_PATH}/{IMAGES_FOLDER_NAME}'
FONTS_FOLDER_PATH = f'{RESOURCES_FOLDER_PATH}/{FONTS_FOLDER_NAME}'
